var annotated =
[
    [ "Camera_System", "class_camera___system.html", "class_camera___system" ],
    [ "Component", "class_component.html", "class_component" ],
    [ "Controllable_Coponent", "class_controllable___coponent.html", "class_controllable___coponent" ],
    [ "CPSProcessSerNum", "struct_c_p_s_process_ser_num.html", "struct_c_p_s_process_ser_num" ],
    [ "Drawable_Component", "class_drawable___component.html", "class_drawable___component" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "Game_Manager", "class_game___manager.html", "class_game___manager" ],
    [ "Message_Handler", "class_message___handler.html", "class_message___handler" ],
    [ "Movement_System", "class_movement___system.html", "class_movement___system" ],
    [ "n8", "classn8.html", "classn8" ],
    [ "Name_Component", "class_name___component.html", "class_name___component" ],
    [ "NSApplication(SDL_Missing_Methods)", "category_n_s_application_07_s_d_l___missing___methods_08.html", "category_n_s_application_07_s_d_l___missing___methods_08" ],
    [ "NSApplication(SDLApplication)", "category_n_s_application_07_s_d_l_application_08.html", null ],
    [ "NSString(ReplaceSubString)", "category_n_s_string_07_replace_sub_string_08.html", null ],
    [ "Point", "class_point.html", "class_point" ],
    [ "Position_Component", "class_position___component.html", "class_position___component" ],
    [ "Render_System", "class_render___system.html", "class_render___system" ],
    [ "Resource_Handler", "class_resource___handler.html", "class_resource___handler" ],
    [ "SDLMain", "interface_s_d_l_main.html", null ],
    [ "Size_Component", "class_size___component.html", "class_size___component" ],
    [ "Sprite", "class_sprite.html", "class_sprite" ],
    [ "System", "class_system.html", "class_system" ]
];